language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

cache:
    directories:
        - "${HOME}/.composer/cache"

install:
    - |
        if dpkg --validate-version "${TRAVIS_PHP_VERSION}" 2>/dev/null && dpkg --compare-versions "${TRAVIS_PHP_VERSION}" ge 7.2; then
            sed -i -e 's#^\s*\$this->assertInternalType(.array., \$arrayOf);$#$this->assertIsArray($arrayOf);#' tests/ContainerTest.php
            travis_retry composer require --no-interaction --prefer-dist --dev "phpunit/phpunit:^8.0"
        elif [ "${TRAVIS_PHP_VERSION} == nightly ]; then
            sed -i -e 's#^\s*\$this->assertInternalType(.array., \$arrayOf);$#$this->assertIsArray($arrayOf);#' tests/ContainerTest.php
            travis_retry composer require --no-interaction --prefer-dist --dev --ignore-platform-reqs "phpunit/phpunit:^9.3"
        else
            travis_retry composer install --no-interaction --prefer-dist
        fi

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
