# TravisCI configuration for thephpleague/container
language: php
os:
  - linux
dist: xenial

php:
    - 7.4
    - 7.3
    - 7.2
    - 7.1
    - 7.0
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

cache:
    directories:
        - "${HOME}/.composer/cache"

install:
    - |
        # Instal PHPUnit v9 on PHP 8
        if [ "${TRAVIS_PHP_VERSION}" == nightly ]; then
            sed -i -e 's#^\s*\$this->assertInternalType(.array., \$arrayOf);$#$this->assertIsArray($arrayOf);#' tests/ContainerTest.php
            travis_retry composer require --no-interaction --prefer-dist --dev --ignore-platform-reqs "phpunit/phpunit:^9.3"
        # Install PHPUnit v8 on PHP 7.2+
        elif dpkg --compare-versions "${TRAVIS_PHP_VERSION}" ge 7.2; then
            sed -i -e 's#^\s*\$this->assertInternalType(.array., \$arrayOf);$#$this->assertIsArray($arrayOf);#' tests/ContainerTest.php
            travis_retry composer require --no-interaction --prefer-dist --dev "phpunit/phpunit:^8.0"
      elif dpkg --compare-versions "${TRAVIS_PHP_VERSION}" ge 7.4; then
            sed -i -e 's#^\s*\$this->assertInternalType(.array., \$arrayOf);$#$this->assertIsArray($arrayOf);#' tests/ContainerTest.php
            sed -i -e 's#^\s*\\/\/ \$foo = $container->call(fn (Foo \$foo) => \$foo);$#\$foo = $container->call(fn (Foo \$foo) => \$foo);#' tests/ReflectionContainerTest.php
            travis_retry composer require --no-interaction --prefer-dist --dev "phpunit/phpunit:^8.0"
        # Keep PHPUnit v6 on PHP 7.1-
        else
            travis_retry composer install --no-interaction --prefer-dist
        fi

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
